// Yusuf.Zerdazi.Web/angular-project/src/app/shared/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
    constructor() { 
    }
}
<footer class="footer">
    <div class="container">
        <span class="footer-bg">
            <a href="https://linkedin.com/in/yusufzerdazi" title="LinkedIn"><i class="fab fa-2x fa-fw fa-linkedin social"></i></a>
            <a href="https://github.com/yusufzerdazi" title="GitHub"><i class="fab fa-2x fa-fw fa-github social"></i></a>
            <a href="https://facebook.com/yusufzerdazi" title="Facebook"><i class="fab fa-2x fa-fw fa-facebook social"></i></a>
            <a href="https://twitter.com/yusufzerdazi" title="Twitter"><i class="fab fa-2x fa-fw fa-twitter social"></i></a>
            <a href="https://soundcloud.com/yusufzerdazi" title="Soundcloud"><i class="fab fa-2x fa-fw fa-soundcloud social"></i></a>
        </span>
    </div>
</footer>

// src/Footer.tsx
function Footer() {
    return (
        <footer className="h-10 mx-auto">
          <div>
            <a className="px-1 hover:opacity-70" href="https://linkedin.com/in/yusufzerdazi" title="LinkedIn">
              <i className="fab fa-linkedin fa-2x"/>
            </a>
            <a className="px-1 hover:opacity-70" href="https://github.com/yusufzerdazi" title="GitHub">
              <i className="fab fa-github fa-2x"/>
            </a>
            <a className="px-1 hover:opacity-70" href="https://www.youtube.com/channel/UCTZsbno68JdiCQbL_6sjdzg" title="YouTube">
              <i className="fab fa-youtube fa-2x"/>
            </a>
            <a className="px-1 hover:opacity-70" href="https://yusufzerdazi.bandcamp.com" title="Bandcamp">
              <i className="fab fa-bandcamp fa-2x"/>
            </a>
            <a className="px-1 hover:opacity-70" href="https://soundcloud.com/yusufzerdazi" title="Soundcloud">
              <i className="fab fa-soundcloud fa-2x"/>
            </a>
          </div>
        </footer>
    );
}

export default Footer;
